-- MySQL Script generated by MySQL Workbench
-- Mon Sep 27 20:22:14 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipo_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tipo_usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tipo_usuario` (
  `idtipo_usuario` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`idtipo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `iduser` INT(9) NOT NULL,
  `name` VARCHAR(255) NULL,
  `email` VARCHAR(155) NULL,
  `password` VARCHAR(255) NULL,
  `idtipo_usuario` INT NOT NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_user_tipo_usuario1_idx` (`idtipo_usuario` ASC),
  CONSTRAINT `fk_user_tipo_usuario1`
    FOREIGN KEY (`idtipo_usuario`)
    REFERENCES `mydb`.`tipo_usuario` (`idtipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pais` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pais` (
  `idpais` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NULL,
  PRIMARY KEY (`idpais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`estado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`estado` (
  `idestado` INT(9) NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `idpais` INT NOT NULL,
  PRIMARY KEY (`idestado`),
  INDEX `fk_estado_pais1_idx` (`idpais` ASC),
  CONSTRAINT `fk_estado_pais1`
    FOREIGN KEY (`idpais`)
    REFERENCES `mydb`.`pais` (`idpais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cidade` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cidade` (
  `idcidade` INT(9) NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `idestado` INT NOT NULL,
  PRIMARY KEY (`idcidade`),
  INDEX `fk_cidade_estado_idx` (`idestado` ASC),
  CONSTRAINT `fk_cidade_estado`
    FOREIGN KEY (`idestado`)
    REFERENCES `mydb`.`estado` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`profile` ;

CREATE TABLE IF NOT EXISTS `mydb`.`profile` (
  `idprofile` INT(9) NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `estado_civil` VARCHAR(45) NULL,
  `rg` VARCHAR(45) NULL,
  `cpf` VARCHAR(45) NULL,
  `telfone` VARCHAR(45) NULL,
  `data_nasc` DATE NULL,
  `idcidade` INT NOT NULL,
  `iduser` INT NOT NULL,
  PRIMARY KEY (`idprofile`),
  INDEX `fk_profile_cidade1_idx` (`idcidade` ASC),
  INDEX `fk_profile_user1_idx` (`iduser` ASC),
  CONSTRAINT `fk_profile_cidade1`
    FOREIGN KEY (`idcidade`)
    REFERENCES `mydb`.`cidade` (`idcidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profile_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`grupo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`grupo` (
  `idgrupo` INT(9) NOT NULL,
  `titulo` VARCHAR(255) NULL,
  `descricao` LONGTEXT NULL,
  `data_inicio` DATE NULL,
  `data_final` DATE NULL,
  `qtd_integrantes` INT(9) NULL,
  `grupocol` VARCHAR(45) NULL,
  PRIMARY KEY (`idgrupo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_grupo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_grupo` (
  `user_iduser` INT(9) NOT NULL,
  `grupo_idgrupo` INT(9) NOT NULL,
  PRIMARY KEY (`user_iduser`, `grupo_idgrupo`),
  INDEX `fk_user_has_grupo_grupo1_idx` (`grupo_idgrupo` ASC),
  INDEX `fk_user_has_grupo_user1_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_user_has_grupo_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_grupo_grupo1`
    FOREIGN KEY (`grupo_idgrupo`)
    REFERENCES `mydb`.`grupo` (`idgrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_destino`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tipo_destino` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tipo_destino` (
  `idtipo_destino` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NULL,
  PRIMARY KEY (`idtipo_destino`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`destino`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`destino` ;

CREATE TABLE IF NOT EXISTS `mydb`.`destino` (
  `iddestino` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  `descricao` LONGTEXT NULL,
  `curiosidades` LONGTEXT NULL,
  `valor` FLOAT NULL,
  `idtipo_destino` INT NOT NULL,
  PRIMARY KEY (`iddestino`),
  INDEX `fk_destino_tipo_destino1_idx` (`idtipo_destino` ASC),
  CONSTRAINT `fk_destino_tipo_destino1`
    FOREIGN KEY (`idtipo_destino`)
    REFERENCES `mydb`.`tipo_destino` (`idtipo_destino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cidade_destino`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cidade_destino` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cidade_destino` (
  `cidade_idcidade` INT(9) NOT NULL,
  `destino_iddestino` INT NOT NULL,
  PRIMARY KEY (`cidade_idcidade`, `destino_iddestino`),
  INDEX `fk_cidade_has_destino_destino1_idx` (`destino_iddestino` ASC),
  INDEX `fk_cidade_has_destino_cidade1_idx` (`cidade_idcidade` ASC),
  CONSTRAINT `fk_cidade_has_destino_cidade1`
    FOREIGN KEY (`cidade_idcidade`)
    REFERENCES `mydb`.`cidade` (`idcidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cidade_has_destino_destino1`
    FOREIGN KEY (`destino_iddestino`)
    REFERENCES `mydb`.`destino` (`iddestino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`grupo_destino`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`grupo_destino` ;

CREATE TABLE IF NOT EXISTS `mydb`.`grupo_destino` (
  `grupo_idgrupo` INT(9) NOT NULL,
  `destino_iddestino` INT NOT NULL,
  PRIMARY KEY (`grupo_idgrupo`, `destino_iddestino`),
  INDEX `fk_grupo_has_destino_destino1_idx` (`destino_iddestino` ASC),
  INDEX `fk_grupo_has_destino_grupo1_idx` (`grupo_idgrupo` ASC),
  CONSTRAINT `fk_grupo_has_destino_grupo1`
    FOREIGN KEY (`grupo_idgrupo`)
    REFERENCES `mydb`.`grupo` (`idgrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupo_has_destino_destino1`
    FOREIGN KEY (`destino_iddestino`)
    REFERENCES `mydb`.`destino` (`iddestino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_destino`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_destino` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_destino` (
  `iduser_destino` INT NOT NULL AUTO_INCREMENT,
  `user_iduser` INT(9) NOT NULL,
  `destino_iddestino` INT NOT NULL,
  PRIMARY KEY (`iduser_destino`, `user_iduser`, `destino_iddestino`),
  INDEX `fk_user_has_destino_destino1_idx` (`destino_iddestino` ASC),
  INDEX `fk_user_has_destino_user1_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_user_has_destino_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_destino_destino1`
    FOREIGN KEY (`destino_iddestino`)
    REFERENCES `mydb`.`destino` (`iddestino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
